# Terms that indicate accessories or components which should be excluded
# from the price statistics (case-insensitive).
exclude_terms:
  - erweiterung
  - expansion
  - insert
  - organizer
  - sleeve
  - sleeves
  - einsatz
  - ersatzteil
  - ersatzteile
  - promo
  - upgrade
  - coins
  - münzen
  - spielmatte
  - playmat
  - inlay
  - aufbewahrung
  - storage
  - standee
  - minis

# eBay condition IDs that count as "new" and are stored in the statistics.
# 1000 = New, 1500 = New other, 1750 = New with defects
condition_ids:
  - 1000
  - 1500
  - 1750

# Require offers to come from this seller account type to filter out private
# listings.
seller_account_type: BUSINESS

# Limit offers to items located in these countries (ISO codes)
item_location_countries:
  - DE

# eBay marketplace and currency settings
marketplace_id: EBAY_DE
price_currency: EUR

# Default eBay category for searches (board games)
default_ebay_category_id: 180349
