name: Build & Deploy
on:
  push:
    branches: [ main ]
  schedule:
    - cron: "17 5 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Fetch offers (eBay wenn Keys vorhanden)
        env:
          EBAY_CLIENT_ID: ${{ secrets.EBAY_CLIENT_ID }}
          EBAY_CLIENT_SECRET: ${{ secrets.EBAY_CLIENT_SECRET }}
          EPN_CAMPAIGN_ID: ${{ secrets.EPN_CAMPAIGN_ID }}
          EPN_REFERENCE_ID: ${{ secrets.EPN_REFERENCE_ID }}
        run: |
          if [ -n "${EBAY_CLIENT_ID}" ] && [ -n "${EBAY_CLIENT_SECRET}" ]; then
            python scripts/fetch_offers_ebay_enhanced.py || true
          else
            python scripts/fetch_offers_stub.py
          fi
      - name: Build site
        env:
          SITE_URL: ${{ secrets.SITE_URL }}
        run: python scripts/build.py
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
