name: PR Preview (GitHub Pages)

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pr-preview-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build:
    if: ${{ github.event.action != 'closed' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Falls Secrets in PRs fehlen (z. B. bei Forks), läuft der Stub weiter.
      - name: Fetch offers (eBay wenn Keys vorhanden)
        env:
          EBAY_CLIENT_ID: ${{ secrets.EBAY_CLIENT_ID }}
          EBAY_CLIENT_SECRET: ${{ secrets.EBAY_CLIENT_SECRET }}
          EPN_CAMPAIGN_ID: ${{ secrets.EPN_CAMPAIGN_ID }}
          EPN_REFERENCE_ID: ${{ secrets.EPN_REFERENCE_ID }}
        run: |
          if [ -n "${EBAY_CLIENT_ID}" ] && [ -n "${EBAY_CLIENT_SECRET}" ]; then
            python scripts/fetch_offers_ebay_enhanced.py || true
          else
            python scripts/fetch_offers_stub.py
          fi

      # WICHTIG: Preview-Basis-URL auf den Unterordner setzen
      - name: Build site (Preview)
        env:
          SITE_URL: https://dom8888912.github.io/${{ github.event.repository.name }}/pr-preview/pr-${{ github.event.pull_request.number }}/
        run: python scripts/build.py

      # <base>-Tag injizieren, damit relative Pfade/CSS/JS im Unterordner funktionieren
      - name: Inject <base> hr
